services:
    - docker
before_script:
    - docker build -t run_tests --target tester .
env:
  global:
     - COMMIT=${TRAVIS_COMMIT::6}
     - REPO=$DOCKER_USER/test-2
script:
    - docker build -t $REPO:$COMMIT --build-arg COMMIT_SHA=$TRAVIS_COMMIT .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
    - docker push $REPO:$TRAVIS_BUILD_NUMBER
    - docker tag $REPO:$COMMIT $REPO:latest
    - docker push $REPO:latest
